# Generated by Django 3.0.8 on 2020-08-04 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_post_wholiked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='whoLiked',
        ),
        migrations.AddField(
            model_name='post',
            name='whoLiked',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
