# Generated by Django 3.0.8 on 2020-08-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20200803_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(null=True, to='network.Comments'),
        ),
    ]
